name: Update Contributors List

on:
  schedule:
    - cron: '0 13 * * 1'
  workflow_dispatch:

permissions:
  contents: write

env:
  token: ${{ secrets.GITHUB_TOKEN }}

jobs:
  update_contributors_list:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set executable permissions for the script
        run: chmod +x ./get-all.sh

      - name: Run the script
        run: |
          ./get-all.sh
      
      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "chore: Update Contributors List"
          git push
